<%@ Page Title="Give Help" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Donate.aspx.cs" Inherits="Food_insecurity__ASPN.NET_.Donate" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">Give Help</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentButtons" runat="server"></asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="MainHeader" runat="server"></asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<div class="donation-page">
  <div class="section-heading"><span class="eyebrow">Give help South Africa</span><h1>Offer food or useful items</h1><p class="lead">Tell FoodCare what you would like to contribute. Use South African contact and address details so that a follow-up can be practical.</p></div>
  <div class="form-card">
    <div class="form-grid">
      <div class="field"><label for="txtName">Name</label><asp:TextBox ID="txtName" runat="server" CssClass="input" MaxLength="100" /><asp:RequiredFieldValidator ID="RequiredFieldValidatorName" runat="server" CssClass="validation" ErrorMessage="Please enter your name." ControlToValidate="txtName" /></div>
      <div class="field"><label for="txtSurname">Surname</label><asp:TextBox ID="txtSurname" runat="server" CssClass="input" MaxLength="100" /><asp:RequiredFieldValidator ID="RequiredFieldValidatorSurname" runat="server" CssClass="validation" ErrorMessage="Please enter your surname." ControlToValidate="txtSurname" /></div>
      <div class="field"><label for="txtPhone">South African phone number</label><asp:TextBox ID="txtPhone" runat="server" CssClass="input" MaxLength="20" placeholder="e.g. 082 123 4567" /><asp:RequiredFieldValidator ID="RequiredFieldValidatorCell" runat="server" CssClass="validation" ErrorMessage="Please enter a phone number." ControlToValidate="txtPhone" /></div>
      <div class="field"><label for="txtEmail">Email address</label><asp:TextBox ID="txtEmail" runat="server" CssClass="input" TextMode="Email" MaxLength="150" /><asp:RequiredFieldValidator ID="RequiredFieldValidatorEmail" runat="server" CssClass="validation" ErrorMessage="Please enter an email address." ControlToValidate="txtEmail" /><asp:RegularExpressionValidator ID="RegularExpressionValidatorEmail" runat="server" CssClass="validation" ErrorMessage="Please enter a valid email address." ControlToValidate="txtEmail" ValidationExpression="^[^\s@]+@[^\s@]+\.[^\s@]+$" /></div>
      <div class="field"><label for="txtItems">Number of items</label><asp:TextBox ID="txtItems" runat="server" CssClass="input" TextMode="Number" min="1" max="100000" /><asp:RequiredFieldValidator ID="RequiredFieldValidatorNumber" runat="server" CssClass="validation" ErrorMessage="Enter the number of items." ControlToValidate="txtItems" /></div>
      <div class="field full"><label>South African address</label><asp:TextBox ID="txtAddress1" runat="server" CssClass="input" placeholder="Street / house number" MaxLength="150" /><asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" CssClass="validation" ErrorMessage="Enter your address." ControlToValidate="txtAddress1" /><asp:TextBox ID="txtAddress2" runat="server" CssClass="input" placeholder="Suburb / town / city" MaxLength="150" /><asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" CssClass="validation" ErrorMessage="Enter your town or city." ControlToValidate="txtAddress2" /><asp:TextBox ID="txtAddress3" runat="server" CssClass="input" placeholder="Province" MaxLength="80" /><asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" CssClass="validation" ErrorMessage="Enter your province." ControlToValidate="txtAddress3" /></div>
      <div class="field full"><label for="txtComment">What are you donating?</label><asp:TextBox ID="txtComment" runat="server" CssClass="input" TextMode="MultiLine" Rows="6" MaxLength="1000" placeholder="Example: 20 sealed 2kg bags of rice, 10 tins of beans, best-before dates included." /><asp:RequiredFieldValidator ID="RequiredFieldValidatorComment" runat="server" CssClass="validation" ErrorMessage="Please describe your donation." ControlToValidate="txtComment" /></div>
      <div class="field"><label for="FileUpload1">Optional image</label><asp:FileUpload ID="FileUpload1" runat="server" CssClass="input" accept="image/jpeg,image/png,image/gif" /><small>JPG, PNG or GIF. Maximum 5 MB.</small></div>
      <div class="field"><label>Delivery method</label><asp:RadioButtonList ID="RadioButtonList1" runat="server"><asp:ListItem Selected="True">Collection from my address</asp:ListItem><asp:ListItem>I can deliver</asp:ListItem></asp:RadioButtonList></div>
      <div class="field"><label for="txtDate">Preferred date and time</label><asp:TextBox ID="txtDate" runat="server" CssClass="input" TextMode="DateTimeLocal" /><asp:RequiredFieldValidator ID="RequiredFieldValidatorDate" runat="server" CssClass="validation" ErrorMessage="Please select a date and time." ControlToValidate="txtDate" /></div>
    </div>
    <div class="form-actions"><asp:Button ID="btnSubmit" CssClass="submit-btn" runat="server" Text="Submit offer" OnClick="btnSubmit_Click" /><asp:Button ID="btnReset" CssClass="secondary-btn" runat="server" Text="Clear" CausesValidation="False" OnClick="btnReset_Click" /><asp:Label ID="lblOutput" runat="server" CssClass="message" /></div>
  </div>
</div>
</asp:Content>
